# Generated by Django 5.0.7 on 2024-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_menuitem_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="category",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="categories",
            field=models.ManyToManyField(to="app.category"),
        ),
    ]
