# Generated by Django 5.0.7 on 2024-08-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_menuitem_category_menuitem_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
