# Generated by Django 5.0.7 on 2024-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="highlight_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
